# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  GLEW_config = debug
  STB_config = debug
  ImGui_config = debug
  NigoziEngine_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  GLEW_config = release
  STB_config = release
  ImGui_config = release
  NigoziEngine_config = release
  Sandbox_config = release

else ifeq ($(config),distribution)
  GLFW_config = distribution
  GLEW_config = distribution
  STB_config = distribution
  ImGui_config = distribution
  NigoziEngine_config = distribution
  Sandbox_config = distribution

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW GLEW STB ImGui NigoziEngine Sandbox

.PHONY: all clean help $(PROJECTS) Core Dependencies Misc

all: $(PROJECTS)

Core: NigoziEngine

Dependencies: GLEW GLFW ImGui STB

Misc: Sandbox

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/glfw -f Makefile config=$(GLFW_config)
endif

GLEW:
ifneq (,$(GLEW_config))
	@echo "==== Building GLEW ($(GLEW_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/glew -f Makefile config=$(GLEW_config)
endif

STB:
ifneq (,$(STB_config))
	@echo "==== Building STB ($(STB_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/stb -f Makefile config=$(STB_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C dependencies/imgui -f Makefile config=$(ImGui_config)
endif

NigoziEngine: GLEW GLFW STB ImGui
ifneq (,$(NigoziEngine_config))
	@echo "==== Building NigoziEngine ($(NigoziEngine_config)) ===="
	@${MAKE} --no-print-directory -C NigoziEngine -f Makefile config=$(NigoziEngine_config)
endif

Sandbox: NigoziEngine GLEW GLFW STB ImGui
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C dependencies/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C dependencies/glew -f Makefile clean
	@${MAKE} --no-print-directory -C dependencies/stb -f Makefile clean
	@${MAKE} --no-print-directory -C dependencies/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C NigoziEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  distribution"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   GLEW"
	@echo "   STB"
	@echo "   ImGui"
	@echo "   NigoziEngine"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"