<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <TargetFramework>net9.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Configurations>Debug;Release;Distribution</Configurations>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>..\Kakali\src\res\scripts\</OutputPath>
    <IntermediateOutputPath>..\Kakali\src\res\scripts\bin-int\Debug\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
    <OutputPath>..\Kakali\src\res\scripts\</OutputPath>
    <IntermediateOutputPath>..\Kakali\src\res\scripts\bin-int\Release\</IntermediateOutputPath>
    <DefineConstants></DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </ItemGroup>
  <ItemGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Source\Nigozi\IScriptBehaviour.cs" />
    <Compile Include="Source\Nigozi\IVector2.cs" />
    <Compile Include="Source\Nigozi\Input.cs" />
    <Compile Include="Source\Nigozi\InternalCalls.cs" />
    <Compile Include="Source\Nigozi\Log.cs" />
    <Compile Include="Source\Nigozi\Nodes\AudioStreamPlayerNode.cs" />
    <Compile Include="Source\Nigozi\Nodes\CameraNode.cs" />
    <Compile Include="Source\Nigozi\Nodes\Node.cs" />
    <Compile Include="Source\Nigozi\Nodes\NodeTypes.cs" />
    <Compile Include="Source\Nigozi\Nodes\RigidbodyNode.cs" />
    <Compile Include="Source\Nigozi\Nodes\SceneNode.cs" />
    <Compile Include="Source\Nigozi\Nodes\SpriteNode.cs" />
    <Compile Include="Source\Nigozi\SceneTree.cs" />
    <Compile Include="Source\Nigozi\Test.cs" />
    <Compile Include="Source\Nigozi\Transform.cs" />
    <Compile Include="Source\Nigozi\Vector2.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\vendor\Coral\Coral.Managed\Coral.Managed.csproj">
      <Project>{11178401-7DD7-FF37-4612-49B5B2914414}</Project>
      <Name>Coral.Managed</Name>
    </ProjectReference>
  </ItemGroup>
</Project>